apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mediawiki.fullname" . }}-db-pvc
spec:
  {{- if .Values.persistence.storageClassName }}{{ cat "storageClassName:" .Values.persistence.storageClassName | nindent 2 }}{{ end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.db }}
