apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mediawiki.fullname" . }}-secrets
  labels:
    {{- include "mediawiki.labels" . | nindent 4 }}
type: Opaque
data:
  wikiadminpw: {{ .Values.wiki.adminpw | b64enc | quote }}
  dbrootpw: {{ .Values.db.rootpw | b64enc | quote }}
  dbuserpw: {{ .Values.db.dbuserpw | b64enc | quote }}
