apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki.fullname" . }}-app
  labels:
    {{- include "mediawiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.app.nginx.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mediawiki.selectorLabels" . | nindent 4 }}
    app: {{ .Chart.Name }}-app
