apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediawiki.fullname" . }}-db
  labels:
    {{- include "mediawiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      protocol: TCP
      name: db
  selector:
    {{- include "mediawiki.selectorLabels" . | nindent 4 }}
    app: {{ .Chart.Name }}-db
